### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by koipkoi** [koipkoi/srmahjongd#3]
## 기본
- [ ] makefile 구성
- [ ] ld_script 작성

## data
- [ ] data ld_script 작성
- [ ] 하드코딩된 data 영역 주소 라벨입력
